version: '3'
services:
  yaanswersload:
    build: .
    command: python3 main.py
    volumes:
      - '.:/app'
    ports:
      - 8888:8888
    depends_on:
      - answersdb
  answersdb:
    image: mysql:5.7
    ports:
        - "3307:3306"
    volumes:
        - "./data:/var/lib/mysql"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: fgh34Hgasd
        MYSQL_DATABASE: ya_answers
        MYSQL_USER: dev
        MYSQL_PASSWORD: dev777

